-- Ligações de voz em grupo (WebRTC mesh), limitadas a membros do grupo.
-- Até 15 participantes podem ficar com status "joined" ao mesmo tempo.

create table if not exists public.chamadas_grupo (
    id uuid primary key default gen_random_uuid(),
    grupo_id uuid not null references public.grupos(id) on delete cascade,
    criado_por text not null,
    status text not null default 'active'
        check (status in ('active','ended')),
    created_at timestamptz not null default now(),
    ended_at timestamptz,
    updated_at timestamptz not null default now()
);

create unique index if not exists chamadas_grupo_uma_ativa_por_grupo
    on public.chamadas_grupo (grupo_id)
    where status = 'active';

create index if not exists chamadas_grupo_grupo_status_idx
    on public.chamadas_grupo (grupo_id, status, created_at desc);

create table if not exists public.chamadas_grupo_participantes (
    chamada_id uuid not null references public.chamadas_grupo(id) on delete cascade,
    usuario_email text not null,
    status text not null default 'invited'
        check (status in ('invited','joined','rejected','left')),
    joined_at timestamptz,
    left_at timestamptz,
    updated_at timestamptz not null default now(),
    primary key (chamada_id, usuario_email)
);

create index if not exists chamadas_grupo_participantes_usuario_idx
    on public.chamadas_grupo_participantes (usuario_email, status, chamada_id);

create table if not exists public.chamadas_grupo_sinais (
    id bigint generated by default as identity primary key,
    chamada_id uuid not null references public.chamadas_grupo(id) on delete cascade,
    de_email text not null,
    para_email text not null,
    tipo text not null check (tipo in ('offer','answer','ice')),
    payload jsonb not null,
    created_at timestamptz not null default now()
);

create index if not exists chamadas_grupo_sinais_destino_idx
    on public.chamadas_grupo_sinais (chamada_id, para_email, id);

alter table public.chamadas_grupo enable row level security;
alter table public.chamadas_grupo_participantes enable row level security;
alter table public.chamadas_grupo_sinais enable row level security;

drop policy if exists "whatisapp_group_calls_select" on public.chamadas_grupo;
drop policy if exists "whatisapp_group_calls_insert" on public.chamadas_grupo;
drop policy if exists "whatisapp_group_calls_update" on public.chamadas_grupo;
create policy "whatisapp_group_calls_select"
on public.chamadas_grupo for select to anon, authenticated using (true);
create policy "whatisapp_group_calls_insert"
on public.chamadas_grupo for insert to anon, authenticated with check (true);
create policy "whatisapp_group_calls_update"
on public.chamadas_grupo for update to anon, authenticated using (true) with check (true);

drop policy if exists "whatisapp_group_call_participants_select" on public.chamadas_grupo_participantes;
drop policy if exists "whatisapp_group_call_participants_insert" on public.chamadas_grupo_participantes;
drop policy if exists "whatisapp_group_call_participants_update" on public.chamadas_grupo_participantes;
create policy "whatisapp_group_call_participants_select"
on public.chamadas_grupo_participantes for select to anon, authenticated using (true);
create policy "whatisapp_group_call_participants_insert"
on public.chamadas_grupo_participantes for insert to anon, authenticated with check (true);
create policy "whatisapp_group_call_participants_update"
on public.chamadas_grupo_participantes for update to anon, authenticated using (true) with check (true);

drop policy if exists "whatisapp_group_call_signals_select" on public.chamadas_grupo_sinais;
drop policy if exists "whatisapp_group_call_signals_insert" on public.chamadas_grupo_sinais;
create policy "whatisapp_group_call_signals_select"
on public.chamadas_grupo_sinais for select to anon, authenticated using (true);
create policy "whatisapp_group_call_signals_insert"
on public.chamadas_grupo_sinais for insert to anon, authenticated with check (true);

grant select, insert, update on table public.chamadas_grupo to anon, authenticated;
grant select, insert, update on table public.chamadas_grupo_participantes to anon, authenticated;
grant select, insert on table public.chamadas_grupo_sinais to anon, authenticated;
grant usage, select on sequence public.chamadas_grupo_sinais_id_seq to anon, authenticated;

create or replace function public.validar_chamada_grupo_nova()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    if not exists (
        select 1 from public.grupo_membros gm
        where gm.grupo_id = new.grupo_id
          and lower(gm.usuario_email) = lower(new.criado_por)
    ) then
        raise exception 'Somente membro do grupo pode iniciar ligação';
    end if;

    new.updated_at := now();
    return new;
end;
$$;

drop trigger if exists trg_validar_chamada_grupo_nova on public.chamadas_grupo;
create trigger trg_validar_chamada_grupo_nova
before insert on public.chamadas_grupo
for each row execute function public.validar_chamada_grupo_nova();

create or replace function public.preparar_chamada_grupo_update()
returns trigger
language plpgsql
as $$
begin
    new.updated_at := now();
    if new.status = 'ended' and new.ended_at is null then
        new.ended_at := now();
    end if;
    return new;
end;
$$;

drop trigger if exists trg_preparar_chamada_grupo_update on public.chamadas_grupo;
create trigger trg_preparar_chamada_grupo_update
before update on public.chamadas_grupo
for each row execute function public.preparar_chamada_grupo_update();

create or replace function public.criar_participantes_chamada_grupo()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.chamadas_grupo_participantes (
        chamada_id, usuario_email, status, joined_at, updated_at
    )
    select
        new.id,
        gm.usuario_email,
        case when lower(gm.usuario_email)=lower(new.criado_por)
             then 'joined' else 'invited' end,
        case when lower(gm.usuario_email)=lower(new.criado_por)
             then now() else null end,
        now()
    from public.grupo_membros gm
    where gm.grupo_id = new.grupo_id
    on conflict (chamada_id, usuario_email) do nothing;

    return new;
end;
$$;

drop trigger if exists trg_criar_participantes_chamada_grupo on public.chamadas_grupo;
create trigger trg_criar_participantes_chamada_grupo
after insert on public.chamadas_grupo
for each row execute function public.criar_participantes_chamada_grupo();

create or replace function public.criar_mensagem_chamada_grupo()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.mensagens (
        remetente_email, destinatario_email, texto, tipo,
        grupo_id, chamada_id, meta
    ) values (
        new.criado_por, null, '[CHAMADA_GRUPO]', 'chamada_grupo',
        new.grupo_id, new.id,
        jsonb_build_object(
            'tipo_chamada','voz_grupo',
            'status',new.status,
            'criado_por',new.criado_por
        )
    );
    return new;
end;
$$;

drop trigger if exists trg_criar_mensagem_chamada_grupo on public.chamadas_grupo;
create trigger trg_criar_mensagem_chamada_grupo
after insert on public.chamadas_grupo
for each row execute function public.criar_mensagem_chamada_grupo();

create or replace function public.sincronizar_mensagem_chamada_grupo()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    update public.mensagens
       set meta = jsonb_build_object(
            'tipo_chamada','voz_grupo',
            'status',new.status,
            'criado_por',new.criado_por
       )
     where chamada_id = new.id
       and tipo = 'chamada_grupo';
    return new;
end;
$$;

drop trigger if exists trg_sincronizar_mensagem_chamada_grupo on public.chamadas_grupo;
create trigger trg_sincronizar_mensagem_chamada_grupo
after update on public.chamadas_grupo
for each row
when (old.status is distinct from new.status)
execute function public.sincronizar_mensagem_chamada_grupo();

create or replace function public.validar_participante_chamada_grupo()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
    v_grupo_id uuid;
    v_status text;
    v_total integer;
begin
    select grupo_id,status into v_grupo_id,v_status
    from public.chamadas_grupo where id=new.chamada_id;

    if v_grupo_id is null then
        raise exception 'Ligação não encontrada';
    end if;

    if not exists (
        select 1 from public.grupo_membros gm
        where gm.grupo_id=v_grupo_id
          and lower(gm.usuario_email)=lower(new.usuario_email)
    ) then
        raise exception 'Usuário não pertence ao grupo';
    end if;

    if new.status='joined' then
        if v_status <> 'active' then
            raise exception 'Ligação encerrada';
        end if;

        select count(*) into v_total
        from public.chamadas_grupo_participantes p
        where p.chamada_id=new.chamada_id
          and p.status='joined'
          and lower(p.usuario_email)<>lower(new.usuario_email);

        if v_total >= 15 then
            raise exception 'Limite de 15 participantes atingido';
        end if;

        if tg_op='INSERT' or old.status is distinct from 'joined' then
            new.joined_at := now();
        end if;
        new.left_at := null;
    elsif new.status in ('left','rejected') then
        new.left_at := now();
    end if;

    new.updated_at := now();
    return new;
end;
$$;

drop trigger if exists trg_validar_participante_chamada_grupo on public.chamadas_grupo_participantes;
create trigger trg_validar_participante_chamada_grupo
before insert or update on public.chamadas_grupo_participantes
for each row execute function public.validar_participante_chamada_grupo();

create or replace function public.encerrar_chamada_grupo_vazia()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    if old.status='joined' and new.status<>'joined' then
        if not exists (
            select 1 from public.chamadas_grupo_participantes p
            where p.chamada_id=new.chamada_id
              and p.status='joined'
        ) then
            update public.chamadas_grupo
               set status='ended', ended_at=now()
             where id=new.chamada_id and status='active';
        end if;
    end if;
    return new;
end;
$$;

drop trigger if exists trg_encerrar_chamada_grupo_vazia on public.chamadas_grupo_participantes;
create trigger trg_encerrar_chamada_grupo_vazia
after update on public.chamadas_grupo_participantes
for each row execute function public.encerrar_chamada_grupo_vazia();

create or replace function public.validar_sinal_chamada_grupo()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
    v_grupo_id uuid;
    v_status text;
begin
    if lower(new.de_email)=lower(new.para_email) then
        raise exception 'Sinalização para si mesmo não é permitida';
    end if;

    select grupo_id,status into v_grupo_id,v_status
    from public.chamadas_grupo where id=new.chamada_id;

    if v_grupo_id is null or v_status<>'active' then
        raise exception 'Ligação de grupo não está ativa';
    end if;

    if not exists (
        select 1 from public.grupo_membros
        where grupo_id=v_grupo_id
          and lower(usuario_email)=lower(new.de_email)
    ) or not exists (
        select 1 from public.grupo_membros
        where grupo_id=v_grupo_id
          and lower(usuario_email)=lower(new.para_email)
    ) then
        raise exception 'Sinalização fora do grupo';
    end if;

    return new;
end;
$$;

drop trigger if exists trg_validar_sinal_chamada_grupo on public.chamadas_grupo_sinais;
create trigger trg_validar_sinal_chamada_grupo
before insert on public.chamadas_grupo_sinais
for each row execute function public.validar_sinal_chamada_grupo();

create or replace function public.sincronizar_membro_com_chamadas_ativas()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    if tg_op='INSERT' then
        insert into public.chamadas_grupo_participantes (
            chamada_id, usuario_email, status, updated_at
        )
        select cg.id,new.usuario_email,'invited',now()
        from public.chamadas_grupo cg
        where cg.grupo_id=new.grupo_id
          and cg.status='active'
        on conflict (chamada_id,usuario_email) do nothing;
        return new;
    end if;

    if tg_op='DELETE' then
        update public.chamadas_grupo_participantes p
           set status='left', left_at=now(), updated_at=now()
          from public.chamadas_grupo cg
         where p.chamada_id=cg.id
           and cg.grupo_id=old.grupo_id
           and cg.status='active'
           and lower(p.usuario_email)=lower(old.usuario_email)
           and p.status in ('joined','invited');
        return old;
    end if;

    return null;
end;
$$;

drop trigger if exists trg_sincronizar_membro_chamadas_ativas on public.grupo_membros;
create trigger trg_sincronizar_membro_chamadas_ativas
after insert or delete on public.grupo_membros
for each row execute function public.sincronizar_membro_com_chamadas_ativas();

create or replace function public.limpar_sinais_chamada_grupo_encerrada()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    if old.status<>'ended' and new.status='ended' then
        delete from public.chamadas_grupo_sinais where chamada_id=new.id;
    end if;
    return new;
end;
$$;

drop trigger if exists trg_limpar_sinais_chamada_grupo on public.chamadas_grupo;
create trigger trg_limpar_sinais_chamada_grupo
after update on public.chamadas_grupo
for each row execute function public.limpar_sinais_chamada_grupo_encerrada();

alter table public.chamadas_grupo replica identity full;
alter table public.chamadas_grupo_participantes replica identity full;
alter table public.chamadas_grupo_sinais replica identity full;

do $$
begin
    if not exists (
        select 1 from pg_publication_tables
        where pubname='supabase_realtime'
          and schemaname='public'
          and tablename='chamadas_grupo'
    ) then
        alter publication supabase_realtime add table public.chamadas_grupo;
    end if;

    if not exists (
        select 1 from pg_publication_tables
        where pubname='supabase_realtime'
          and schemaname='public'
          and tablename='chamadas_grupo_participantes'
    ) then
        alter publication supabase_realtime add table public.chamadas_grupo_participantes;
    end if;

    if not exists (
        select 1 from pg_publication_tables
        where pubname='supabase_realtime'
          and schemaname='public'
          and tablename='chamadas_grupo_sinais'
    ) then
        alter publication supabase_realtime add table public.chamadas_grupo_sinais;
    end if;
end $$;
