-- Ligações de voz 1x1 via WebRTC + Supabase Realtime

alter table public.mensagens
    add column if not exists chamada_id uuid,
    add column if not exists meta jsonb;

create table if not exists public.chamadas (
    id uuid primary key default gen_random_uuid(),
    tipo text not null default 'voz',
    status text not null default 'ringing',
    chamador_email text not null,
    receptor_email text not null,
    offer jsonb,
    answer jsonb,
    created_at timestamptz not null default now(),
    answered_at timestamptz,
    ended_at timestamptz,
    duracao_segundos integer not null default 0,
    ended_by text,
    updated_at timestamptz not null default now()
);

create table if not exists public.chamada_ice_candidates (
    id bigint generated by default as identity primary key,
    chamada_id uuid not null references public.chamadas(id) on delete cascade,
    remetente_email text not null,
    candidate jsonb not null,
    created_at timestamptz not null default now()
);

create index if not exists chamadas_chamador_status_idx
    on public.chamadas (chamador_email, status, created_at desc);

create index if not exists chamadas_receptor_status_idx
    on public.chamadas (receptor_email, status, created_at desc);

create index if not exists chamada_ice_chamada_idx
    on public.chamada_ice_candidates (chamada_id, id);

create index if not exists mensagens_chamada_idx
    on public.mensagens (chamada_id)
    where chamada_id is not null;

alter table public.chamadas enable row level security;
alter table public.chamada_ice_candidates enable row level security;

drop policy if exists "whatisapp_calls_select" on public.chamadas;
drop policy if exists "whatisapp_calls_insert" on public.chamadas;
drop policy if exists "whatisapp_calls_update" on public.chamadas;

create policy "whatisapp_calls_select"
on public.chamadas for select
to anon, authenticated
using (true);

create policy "whatisapp_calls_insert"
on public.chamadas for insert
to anon, authenticated
with check (true);

create policy "whatisapp_calls_update"
on public.chamadas for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists "whatisapp_call_ice_select" on public.chamada_ice_candidates;
drop policy if exists "whatisapp_call_ice_insert" on public.chamada_ice_candidates;
drop policy if exists "whatisapp_call_ice_delete" on public.chamada_ice_candidates;

create policy "whatisapp_call_ice_select"
on public.chamada_ice_candidates for select
to anon, authenticated
using (true);

create policy "whatisapp_call_ice_insert"
on public.chamada_ice_candidates for insert
to anon, authenticated
with check (true);

create policy "whatisapp_call_ice_delete"
on public.chamada_ice_candidates for delete
to anon, authenticated
using (true);

create or replace function public.preparar_estado_chamada()
returns trigger
language plpgsql
as $$
begin
    new.updated_at := now();

    if new.status = 'active' and new.answered_at is null then
        new.answered_at := now();
    end if;

    if new.status in ('ended', 'cancelled', 'rejected', 'missed', 'failed') then
        if new.ended_at is null then
            new.ended_at := now();
        end if;

        if new.answered_at is not null and coalesce(new.duracao_segundos, 0) <= 0 then
            new.duracao_segundos :=
                greatest(0, floor(extract(epoch from (new.ended_at - new.answered_at)))::integer);
        end if;
    end if;

    return new;
end;
$$;

drop trigger if exists trg_preparar_estado_chamada on public.chamadas;
create trigger trg_preparar_estado_chamada
before update on public.chamadas
for each row
execute function public.preparar_estado_chamada();

create or replace function public.criar_mensagem_da_chamada()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.mensagens (
        remetente_email,
        destinatario_email,
        texto,
        tipo,
        chamada_id,
        meta
    ) values (
        new.chamador_email,
        new.receptor_email,
        '[CHAMADA]',
        'chamada',
        new.id,
        jsonb_build_object(
            'tipo_chamada', new.tipo,
            'status', new.status,
            'duracao_segundos', coalesce(new.duracao_segundos, 0),
            'chamador_email', new.chamador_email,
            'receptor_email', new.receptor_email
        )
    );

    return new;
end;
$$;

drop trigger if exists trg_criar_mensagem_da_chamada on public.chamadas;
create trigger trg_criar_mensagem_da_chamada
after insert on public.chamadas
for each row
execute function public.criar_mensagem_da_chamada();

create or replace function public.sincronizar_mensagem_da_chamada()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    update public.mensagens
       set meta = jsonb_build_object(
            'tipo_chamada', new.tipo,
            'status', new.status,
            'duracao_segundos', coalesce(new.duracao_segundos, 0),
            'chamador_email', new.chamador_email,
            'receptor_email', new.receptor_email
       )
     where chamada_id = new.id;

    return new;
end;
$$;

drop trigger if exists trg_sincronizar_mensagem_da_chamada on public.chamadas;
create trigger trg_sincronizar_mensagem_da_chamada
after update on public.chamadas
for each row
when (
    old.status is distinct from new.status
    or old.duracao_segundos is distinct from new.duracao_segundos
)
execute function public.sincronizar_mensagem_da_chamada();

alter table public.chamadas replica identity full;
alter table public.chamada_ice_candidates replica identity full;
