-- Diagnóstico temporário das ligações WebRTC.
create table if not exists public.chamada_diagnosticos (
    id bigint generated by default as identity primary key,
    chamada_id uuid not null references public.chamadas(id) on delete cascade,
    usuario_email text not null,
    evento text not null,
    dados jsonb,
    created_at timestamptz not null default now()
);

create index if not exists chamada_diagnosticos_call_idx
    on public.chamada_diagnosticos (chamada_id, created_at);

alter table public.chamada_diagnosticos enable row level security;

drop policy if exists "whatisapp_call_diag_select" on public.chamada_diagnosticos;
drop policy if exists "whatisapp_call_diag_insert" on public.chamada_diagnosticos;

create policy "whatisapp_call_diag_select"
on public.chamada_diagnosticos for select
to anon, authenticated
using (true);

create policy "whatisapp_call_diag_insert"
on public.chamada_diagnosticos for insert
to anon, authenticated
with check (true);

grant select, insert on table public.chamada_diagnosticos to anon, authenticated;
grant usage, select on sequence public.chamada_diagnosticos_id_seq to anon, authenticated;
