-- Ações de mensagem: "apagar para mim".
-- Mantém a mensagem original intacta e registra apenas que este usuário
-- não deve mais vê-la. Ao apagar a mensagem para todos, o vínculo some
-- automaticamente por ON DELETE CASCADE.

create table if not exists public.mensagens_ocultas (
    id bigint generated by default as identity primary key,
    usuario_email text not null,
    mensagem_id bigint not null references public.mensagens(id) on delete cascade,
    created_at timestamp with time zone not null default now(),
    unique (usuario_email, mensagem_id)
);

create index if not exists idx_mensagens_ocultas_usuario
on public.mensagens_ocultas (usuario_email, mensagem_id);
